### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Yrlish** [kappataumu/letsencrypt-cloudflare-hook#12]
In the attached file, you can see the command (taken from the README), and all its output. I don't understand why it's so dumb. :(

File: [error.txt](https://github.com/kappataumu/letsencrypt-cloudflare-hook/files/232464/error.txt)

**Comment by Yrlish** [comment]
It seemed I used python2.7. I installed python3, modified hook.py to use python3 and it worked.

**Comment by kappataumu** [comment]
It should work with Python 2.7, did you install the appropriate requirements?  Check the [installation instructions](https://github.com/kappataumu/letsencrypt-cloudflare-hook#installation):

```
$ pip install -r hooks/cloudflare/requirements-python-2.txt
```

**Comment by kappataumu** [comment]
I think you've sorted it out, if you need any help feel free to reopen.

**Comment by Yrlish** [comment]
Yes, I did. I installed the python3 requirements in python2, didn't work. And when I then tried to install the python2 requirements, it just threw a bunch of errors, so I installed python3 instead with correct dependencies.
