### ISSUE TITLE
Getting stuck at:  + CloudFlare hook executing: deploy_challenge

### ISSUE THREAD

**Issue by zakiaziz** [kappataumu/letsencrypt-cloudflare-hook#14]
Hi, I opened an issue before and resolved the issue. I was able to create a few new certs successfully. I've tried the same script again on a new domain (on the same server as before) and I'm getting this error:

```
# INFO: Using main config file /home/user/letsencrypt.sh/config.sh
Processing mydomain.com
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for mydomain.com...
 + CloudFlare hook executing: deploy_challenge
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 157, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 153, in main
    ops[argv[0]](argv[1:])
  File "hooks/cloudflare/hook.py", line 96, in create_txt_record
    zone_id = _get_zone_id(domain)
  File "hooks/cloudflare/hook.py", line 75, in _get_zone_id
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com
```

**Comment by zakiaziz** [comment]
Removing config.sh  and manually setting my email/api key works. This was the content of my config.sh file:

```
export CF_EMAIL='email@mydomain.cob'
export CF_KEY='cloudflare_global_api_key'
```

Is this issue caused by letsencrypt.sh or letsencrypt-cloudflare-hook?

**Comment by kappataumu** [comment]
Hello, did you resolve this issue? 

I don't think it has to do with either `letsencrypt.sh` or `letsencrypt-cloudflare-hook`. Under the hood `config.sh` is sourced by `letsencrypt.sh`, so as long as the former is valid, it is exactly the same as typing the commands yourself in the shell (or sourcing another file that sets up the environment).

So, you could:

```
export CF_EMAIL='email@mydomain.cob' >> config.sh
export CF_KEY='cloudflare_global_api_key' >> config.sh
mv config.sh conf_test.sh
source conf_test.sh
letsencrypt.sh -c -d domain.com -t dns-01 -k hooks/cloudflare/hook.py'
```

Does the above work? It should, if you are entering the correct credentials.

**Comment by zakiaziz** [comment]
I was incorrectly using config.sh. Thanks!
