### ISSUE TITLE
Been getting 'DNS not propagated, waiting 30s'

### ISSUE THREAD

**Issue by zakiaziz** [kappataumu/letsencrypt-cloudflare-hook#16]
Hi I can't seem to get past this message:

```
 + DNS not propagated, waiting 30s...
 + DNS not propagated, waiting 30s...
...
```

It's been going on for about an hour. Why does this happens and is there a way I can speed it up?

**Comment by kappataumu** [comment]
DNS propagation depends on a number of things, some times an intermediate server caches results. I presume that's what you hit.
