### ISSUE TITLE
Resolved issues

### ISSUE THREAD

**Issue by mscalora** [kappataumu/letsencrypt-cloudflare-hook#17]
I created a hook for the Hover.com registrar based on this great work. I ran into a couple issues in testing on various environments and wanted to contribute back the solutions I found. Both are issues caused by upstream bugs that I wasn't able to work around with the latest version even though the threads imply they are fixed:

First: Some version of Ubuntu don't like the package path of inject_into_urllib3(), I tried all the workarounds involving updates and none worked on my Ubuntu box, the solution I came up with is benign for unaffected users:

```
# Enable verified HTTPS requests on older Pythons 
# http://urllib3.readthedocs.org/en/latest/security.html
if sys.version_info[0] == 2:
    try:
        requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3()
    except AttributeError:
        # see https://github.com/certbot/certbot/issues/1883
        import urllib3.contrib.pyopenssl
        urllib3.contrib.pyopenssl.inject_into_urllib3()
```

Second: I think you inherited this issue from letsencrypt's python certbot, dns.resolver has/had a bug when they went to single source for Py 2 & 3 around byte strings coming back from dns.resolver.query(name, 'TXT')

```
    for rdata in dns_response:
        for txt_record in rdata.strings:
            logger.debug("Found TXT record with the value: '%s'" % txt_record)
            # see https://groups.google.com/d/topic/dnspython-users/bKi_bxL48rI/discussion
            if hasattr(txt_record, 'decode'):
                txt_record = txt_record.decode("utf-8")
            txt_records.append(txt_record)
```

Thanks for the great script to work from.
-Mike

**Comment by kappataumu** [comment]
Good detective skills. 

If you want to submit a pull request for the first part, go ahead. Otherwise I'll get to it next week.

For the second part, I see that the issue has been resolved in https://github.com/rthalley/dnspython/issues/171, so I'll keep this issue open until `1.14.1` is released and then update the requirements.
