### ISSUE TITLE
nxdomain cached in between

### ISSUE THREAD

**Issue by dynek** [kappataumu/letsencrypt-cloudflare-hook#2]
Hey!

Thanks a bunch for your work!
I do have a question: shouldn't _create_txt_record_ be waiting a couple a seconds so that cloudflare "settles down" with the newly created record?
It seems it's being checked a little too quickly resulting in dns cache(s) in between caching nxdomain for the record. Then SOA TTL has to expire before it goes on.

Thank you

**Comment by kappataumu** [comment]
Hello!

Good point, merging. Thanks! :+1:
