### ISSUE TITLE
bytes != str in Python 3

### ISSUE THREAD

**Issue by hexchain** [kappataumu/letsencrypt-cloudflare-hook#22]
https://github.com/kappataumu/letsencrypt-cloudflare-hook/blob/master/hook.py#L70

This will never be true in Python 3 because token is a 'str' but txt_record is 'bytes'.

**Comment by kappataumu** [comment]
Hello! I've been using Python 3 myself, and I haven't hit this, so `txt_record` must have been `str` at least some of the time! :)

This I believe was an issue with `dnspython`, which the latest version (`1.15.0`) should have resolved entirely. The requirements were also updated a few days ago. Can you verify?

**Comment by m3nu** [comment]
I hit the same issue just now. Newly installed virtenv in python3.

Had to add `.decode('ascii')` to force the bytes to string.

Rest works great!

**Comment by m3nu** [comment]
`pip freeze` shows that `dnspython` is at the latest version. Maybe they didn't fix it after all?

```
dnspython==1.15.0
dnspython3==1.15.0
future==0.15.2
requests==2.9.1
six==1.10.0
tld==0.7.6
```

**Comment by kappataumu** [comment]
OK, apparently I was using `1.12.0` in my testing virtualenv. Using `1.15.0` I am hitting it as well. This was reported in #17 but I mistakenly attributed it to an unrelated `dnspython` issue.

It should be good now, could you verify?

**Comment by m3nu** [comment]
Yes. All working. Tested with Python 3 and 2. Thanks for the quick fix.

**Comment by bennettp123** [comment]
Posting this here for anyone who comes in from google.

If anyone sees the error below, try updating to `dnspython3==1.15.0`.

```
Traceback (most recent call last):
  File "/home/letsencrypt/src/letsencrypt.sh.rsa/hooks/cloudflare/hook.py", line 182, in <module>
    main(sys.argv[1:])
  File "/home/letsencrypt/src/letsencrypt.sh.rsa/hooks/cloudflare/hook.py", line 178, in main
    ops[argv[0]](argv[1:])
  File "/home/letsencrypt/src/letsencrypt.sh.rsa/hooks/cloudflare/hook.py", line 161, in create_all_txt_records
    while(_has_dns_propagated(name, token) == False):
  File "/home/letsencrypt/src/letsencrypt.sh.rsa/hooks/cloudflare/hook.py", line 68, in _has_dns_propagated
    if token in [b.decode('utf-8') for b in rdata.strings]:
  File "/home/letsencrypt/src/letsencrypt.sh.rsa/hooks/cloudflare/hook.py", line 68, in <listcomp>
    if token in [b.decode('utf-8') for b in rdata.strings]:
AttributeError: 'str' object has no attribute 'decode'
```

@kappataumu commented,
> [...] `txt_record` must have been `str` at least some of the time! :)

`dnspython3==1.12.0` returns `str`; `dnspython3==1.15.0` returns `bytes`.
