### ISSUE TITLE
400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones/...

### ISSUE THREAD

**Issue by 3dluvr** [kappataumu/letsencrypt-cloudflare-hook#23]
Hi,

Not sure what am I doing wrong here, everything worked fine before I did a git pull to refresh the hook to the latest one.

```
* CloudFlare hook executing: deploy_challenge
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 176, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 172, in main
    ops[argv[0]](argv[1:])
  File "hooks/cloudflare/hook.py", line 148, in create_all_txt_records
    create_txt_record(args[i:i+X])
  File "hooks/cloudflare/hook.py", line 112, in create_txt_record
    r.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones/e8ef854e*snip*3867137/dns_records
```

Running this on Oracle Linux Server 6.8 and tried with both python2.7 and python3.5.

CF_\* env is setup correctly as those settings have not changed since last I run them.

Thanks.

**Comment by kappataumu** [comment]
Hi! I'm seeing this as well. 

It seems to happen when we try to create a new TXT record, but an identical one already exists in CloudFlare. This happens when the verification process for some reason does not complete, the TXT record is not cleaned up and subsequent challenge responses reuse the same token.

Can you verify that if no _acme-challenge records exist before running the hook, the error is not thrown?

**Comment by kappataumu** [comment]
I've pushed a fix, let me know if it works for you.

**Comment by 3dluvr** [comment]
Thanks for looking into it.

After pulling the fix, this is what I got:

```
* CloudFlare hook executing: deploy_challenge
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 183, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 179, in main
    ops[argv[0]](argv[1:])
  File "hooks/cloudflare/hook.py", line 155, in create_all_txt_records
    create_txt_record(args[i:i+X])
  File "hooks/cloudflare/hook.py", line 102, in create_txt_record
    logger.debug(' + Creating TXT record: {} => {}'.format(domain, token))
```

I guess that line 102 should've perhaps been:
`logger.debug(' + Creating TXT record: {0} => {1}'.format(domain, token))`

After doing this, dehydrated worked all the way and updated my certs.

Cheers!

**Comment by kappataumu** [comment]
No problem.

Line 102 should be equally valid no matter how you write the placeholders, so I'm wondering if there is another issue. Does the stack trace stop there? If you pull a fresh copy does it still barf?

**Comment by 3dluvr** [comment]
Sorry for a delayed reply, I missed the notification on this post.

Is there a way I can dry-test as my certs are now updated so the hook does not execute?

**Comment by kappataumu** [comment]
Sure, you can use the staging server for Let's Encrypt, by placing this line in your `config` file:

```
CA="https://acme-staging.api.letsencrypt.org/directory"
```

Then proceed as usual, `dehydrated` will generate a new account key and dummy certificates for all your domains, with no rate limits. Do this from a fresh `dehydrated` installation, to keep dummy certs away from production.

**Comment by 3dluvr** [comment]
I cloned dehydrated and the hook into a test folder then ran against the staging server.

Still getting that error _ValueError: zero length field name in format_ from above about logger.debug line 102.

I now realize this is related to me using the default Python 2.6.6.

If I add an alias to python3.5 and change line 1 in hook.py to python3.5, then I do not get that error.

No other errors occur.

**Comment by kappataumu** [comment]
Thank you! I should've tested with Python 2 as well. Will push a fix shortly.

**Comment by kappataumu** [comment]
Should be OK now.
