### ISSUE TITLE
Invalid Challenge Added to Dehydrated

### ISSUE THREAD

**Issue by bitbytenybble110** [kappataumu/letsencrypt-cloudflare-hook#26]
In [Dehydrated Commit: 318cf20](https://github.com/lukas2511/dehydrated/commit/318cf2011d5e024c199d19c9375c66336861ad64) the new invalid_challenge hook was added.  This breaks the letsencrypt-cloudflare-hook.

Adding the following to hooks.py resolves this issue.  This does not handle the invalid_challenge in any way.  It simply allows the hook to return:

```
def invalid_challenge(args):
    return

def main(argv):
    ops = {
        'deploy_challenge': create_all_txt_records,
        'clean_challenge' : delete_all_txt_records,
        'deploy_cert'     : deploy_cert,
        'unchanged_cert'  : unchanged_cert,
	'invalid_challenge': invalid_challenge,
    }
    logger.info(" + CloudFlare hook executing: {0}".format(argv[0]))
    ops[argv[0]](argv[1:])
```

**Comment by kappataumu** [comment]
Thank you, I'll push an update later today.
