### ISSUE TITLE
Use 120 seconds TTL instead of 1

### ISSUE THREAD

**Issue by nh2** [kappataumu/letsencrypt-cloudflare-hook#32]
`1` [means "automatic TTL"](https://api.cloudflare.com/#zone-settings-change-websockets-setting), which according to the [CloudFlare docs](https://support.cloudflare.com/hc/en-us/articles/200168866-What-does-the-Automatic-TTL-value-mean-) means `5 minutes`.

Changing to 120 seconds can reduce the waiting time.

**Comment by nh2** [comment]
PR in #33

**Comment by kappataumu** [comment]
@nh2 Sounds reasonable, merged. Sorry for taking so long!
