### ISSUE TITLE
DNS not propagated

### ISSUE THREAD

**Issue by kmlucy** [kappataumu/letsencrypt-cloudflare-hook#34]
In trying to update a certification, the hook just keeps printing the ```+ DNS not propagated, waiting 30s...``` error. When I go to my Cloudflare account, the TXT has been successfully added. Waiting doesn't help. It has run for several hours without picking up the record.

**Comment by kmlucy** [comment]
Also, I am able to look up the record using other sources. Specifically, mxtoolbox.com is able to pick up the record.

**Comment by whoisearth** [comment]
Did you figure out the issue?  I'm running it with exactly the same issue however I won't have time to dig in the code until later tonite.  Same issue though, the _acme-challenge is visible in my cloudflare account

**Comment by kmlucy** [comment]
I have not figured it out yet. Best I can tell, it's something with the Python DNS resolver, but I'm not super familiar with Python, so I'm not sure.

**Comment by whoisearth** [comment]
are you using 2.7 as well or python 3.x?

**Comment by kmlucy** [comment]
I'm using 3.6.1.

**Comment by kappataumu** [comment]
@kmlucy @whoisearth Can you verify that the TXT record is visible from the machine you are running the hook? Run `dig -t txt example.com`.

**Comment by whoisearth** [comment]
I see the following.

```
; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> -t txt mydomain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1774
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mydomain.com.                  IN      TXT

;; AUTHORITY SECTION:
mydomain.com.           3600    IN      SOA     mydomaincontroller.mydomain.com. hostmaster.mydomain.com. 27 900 600 86400 3600

;; Query time: 2 msec
;; SERVER: 10.77.1.20#53(10.77.1.20)
;; WHEN: Tue Apr 04 09:58:31 EDT 2017
;; MSG SIZE  rcvd: 101

```

**Comment by kmlucy** [comment]
``` 
; <<>> DiG 9.9.5-9+deb8u10-Debian <<>> -t txt kylelucy.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64300
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;kylelucy.com.                  IN      TXT

;; AUTHORITY SECTION:
kylelucy.com.           1240    IN      SOA     aria.ns.cloudflare.com. dns.cloudflare.com. 2024289100 10000 2400 604800 3600

;; Query time: 16 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Tue Apr 04 14:05:52 UTC 2017
;; MSG SIZE  rcvd: 100
```

**Comment by whoisearth** [comment]
looks like the script is failing particularly in trying to find the following:  `os.environ['CF_DNS_SERVERS']` which I know I didn't set was that something I missed in the dehydrated script?  Going back through the docs now.

**Comment by kappataumu** [comment]
You can verify local DNS propagation by cross-checking with Google's DNS servers, like so: `dig @8.8.8.8 -t txt example.com`. Are the records visible there when you hit this issue?

**Comment by kmlucy** [comment]
By setting the ```CF_DNS_SERVERS``` to Google's DNS servers I was able to get it working. I think what was happening was that since the subdomain was my internal domain, my local DNS servers were not sending the request was not being sent out.

**Comment by whoisearth** [comment]
ah cool.  I just setup my cloudflare last night it's possible the propagation hasn't completed yet>  I'm not seeing their dns entries in that search:

```
; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> @8.8.8.8 -t txt mydomain.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10809
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mydomain.com.                  IN      TXT

;; AUTHORITY SECTION:
mydomain.com.           1799    IN      SOA     ns1.dreamhost.com. hostmaster.dreamhost.com. 2017040301 20664 1800 1814400 14400

;; Query time: 92 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Apr 04 10:38:04 EDT 2017
;; MSG SIZE  rcvd: 102
```

**Comment by kappataumu** [comment]
@kmlucy Local DNS servers are often the issue, especially when they've cached stuff. Glad you sorted it.

@whoisearth Ok, try again once the DNS servers are updated to Cloudflare and report back if everything works as it should. Leaving this open for now.
