### ISSUE TITLE
: No such file or directory

### ISSUE THREAD

**Issue by Phomias** [kappataumu/letsencrypt-cloudflare-hook#4]
Because **hooks.py has dos line endings** you get this error when trying to run the py hook script:

```
/usr/bin/env: python
: No such file or directory
```

Please change the line endings to unix style.

(either that or I have something set wrong in my git client and somehow git is changing the line endings to crlf on checkout. But as far as I can tell I don't have core.autocrlf set to true)

**Comment by kappataumu** [comment]
Hello,

I think the problem lies elsewhere, but i am curious as to why you would think line endings make a difference. Could you provide more details?

Are you getting the same error when you run `hook.py` or `python hook.py` directly, from a fresh repo clone, regardless of `letsencrypt.sh`?

**Comment by Phomias** [comment]
Getting errors when I run `hook.py` directly because the problem is specific to the `CRLF` at the end of the shebang line.  `python hook.py` would be ok because it ignores the shebang and python is fine with `CRLF`s. It's also a problem when `letsencrypt.sh` calls `hook.py`.  See here for more info
http://unix.stackexchange.com/questions/189254/no-such-file-or-directory-but-i-can-see-it

**Comment by kappataumu** [comment]
Makes sense, thanks. I'll push a fix shortly.

**Comment by Phomias** [comment]
Awesome. I've only been using git regularly for 9 months so I'll be happy
to have confirmation that it wasn't my git ignorance.
