### ISSUE TITLE
Problem in the cloudflare hook with new dehydrated client.

### ISSUE THREAD

**Issue by vikrantrathore** [kappataumu/letsencrypt-cloudflare-hook#40]
Getting an error with after updating dehydrated to new version.
+ CloudFlare hook executing: startup_hook
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 203, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 199, in main
    ops[argv[0]](argv[1:])
KeyError: 'startup_hook'
Python 3.5.2
Requirement already satisfied: dnspython==1.15.0
Requirement already satisfied: future==0.15.2
Requirement already satisfied: requests==2.9.1
Requirement already satisfied: six==1.10.0
Requirement already satisfied: tld==0.7.6

**Comment by kappataumu** [comment]
Fixed w/ PR https://github.com/kappataumu/letsencrypt-cloudflare-hook/pull/38.
