### ISSUE TITLE
KeyError cloudflare

### ISSUE THREAD

**Issue by kdulep** [kappataumu/letsencrypt-cloudflare-hook#48]
./dehydrated -c -d example.etc -t dns-01 -k 'hooks/cloudflare/hook.py'`

```
# INFO: Using main config file /root/dehydrated/config
 + CloudFlare hook executing: *some key*
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 206, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 202, in main
    ops[argv[0]](argv[1:])
KeyError: '*some key*=='

```

**Comment by louis-lau** [comment]
See Issue #46 and my PR to fix it #47 

Until the PR is merged you could clone [my fork](https://github.com/louis-lau/letsencrypt-cloudflare-hook) and then `git checkout ignore-unknown-hooks`

**Comment by Asara** [comment]
@louis-lau Thanks for the PR. Hope it gets merged soon!

**Comment by kappataumu** [comment]
@louis-lau @Asara Thank you! Merged
